### ISSUE TITLE
Papers We Love #1 - Michael Bernstein on A Uniﬁed Theory of Garbage Collection

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#1]
@mrb
- [meetup](http://www.meetup.com/papers-we-love/events/163406212/)
- [video](https://www.youtube.com/watch?v=XtUtfARSIv8&list=UUoj4eQh_dZR37lL78ymC6XA)
- [audio](http://www.mixcloud.com/paperswelove/mbernstein_02_24_2014_a-unified_theory_of_garbage_collection/)
- [slides](https://speakerdeck.com/paperswelove/michael-bernstein-on-a-unified-theory-of-garbage-collection-by-bacon-cheng-rajan)

This issue has been created to start/spark/organize a conversation on the paper **A Unified Theory of Garbage Collection** by Bacon, Cheng, Rajan. 

Please offer up questions, comments, or additional information regarding this paper. 
- Paper can be found in this [repo](https://github.com/papers-we-love/papers-we-love/blob/master/garbage_collection/README.md) or [here](http://www.cs.virginia.edu/~cs415/reading/bacon-garbage.pdf).

**Comment by jdh30** [comment]
In the lecture you say that garbage collection is "batch, no cost per mutation, has long pause times and is not real-time" and reference counting is "incremental, high cost per mutation, short pause times and is real-time".

Incremental tracing algorithms were introduced in the 1970s and real-time concurrent and parallel GCs exist to day so tracing GC is not necessarily batch and does not necessarily have long pause times and can be real-time.

Immediate reference counting has to deallocate an arbitrary DAG of objects as soon as the last root is decremented to zero which incurs an arbitrarily-long pause so it is not incremental, does not necessarily have short pause times and is not real-time. The unbounded-pause-time problem with immediate reference counting is easily fixed by using deferred reference counting.

Another issue I have (with the original paper as well) is the implication that immediate reference counting does not have floating garbage. It does. Garbage can be created halfway through a callee but the decrement to zero will not occur until the caller returns in which case the garbage is floating until the callee returns.

**Comment by zeeshanlakhani** [comment]
nice to ping @mrb and @aturley here :).
