### ISSUE TITLE
git-annex

### ISSUE THREAD

**Issue by umeboshi2** [papers-we-love/papers-we-love#333]
I just created a "clone" of this repo using git-annex.  The web url's for what's hosted at github are using the github urls.  The readme's can be parsed and the unavailable papers can be added with ```git-annex addurl <upstream url>```.  The repo is about 1 megabyte currently.

https://github.com/umeboshi2/pwl-annex

**Comment by NewAlexandria** [comment]
This doesn't sound like an issue, and no proposal is made. Suggest closing.

**Comment by umeboshi2** [comment]
my issue resolved with git-annex
implied proposal to have alternate git-annex repo
I have pwl in annexation, but made smaller repo for y'all
a checkout of your repo is 300MB, and all must be retrieved at once
read about git-annex
https://git-annex.branchable.com/

**Comment by hakutsuru** [comment]
Please do not imply solutions.

If you have a solution, there must be a problem.

State the problem clearly, and your proposed solution. Seek understanding and consensus, then we can work towards an appropriate solution.

A 300MB download is not a burden to most users of GitHub, and if it is, there is a web interface to obtain any specific content desired.

I do not understand your solution, it appears to create a burden that there be an external archive. Where would this be and who would maintain it?

Open another issue with a more informative discussion of the problem and your proposed solution. This issue was not helpful, and assumes people understand too much implied knowledge and experience.

**Comment by umeboshi2** [comment]
"Seek understanding and consensus, then we can work towards an appropriate solution." -- no need.  my problem has been solved already.  I'm removing the repo since y'all don't understand where it can be useful.  You can still find the info at https://github.com/umeboshi2/annexation/tree/master/papers-we-love in the future, although it's a much larger repo.

**Comment by jeremyheiler** [comment]
@umeboshi2 Could you please clarify why this is usefu? If you think that there is a problem with the repository being to large, why didn't you lead with that, offering reasons why you'd like to see it be smaller? Did you want to merge your changes in? Did you want to host a mirror? It's unclear what your goal is to begin with. That said, we are OK with the size of the repository at this time. If that is not your goal, please clarify your intent.

We appreciate contributions to this repository very much, but we also have a specific direction we would like to go in, and cannot say yes to everything.
