### ISSUE TITLE
Devise JSON metadata format for papers within the repo 

### ISSUE THREAD

**Issue by DarrenN** [papers-we-love/papers-we-love#374]
## Problem

We have little in the way of machine readable data about the contents of the repo
## Potential solution

Device a simple JSON format based on [BibTex](http://www.bibtex.org/Format/), but with additional fields, that we can generate and consume

Related to #52 #20 #310

**Comment by devinmcgloin** [comment]
It seems like the best way to go about this is to standardize the format in which people add papers to the repo in the first place. 

I'm thinking something along the lines of a yaml listing in each directory with the paper title, author, and year published as well as the brief paragraph of why it should be included. We could then add more metadata and standardize filenames from the Microsoft Academic API, and compile those listings down to readme and citation files in each directory. We could also include a helper script to add papers and compile them down in the repo so people can add things all in one step.

## Benefits

- We could possibly add paper search functionality on [paperswelove.org](http://paperswelove.org/).
- As there is a compilation step down to the readme we could date when the papers were added thus solving #310.
- It would be simpler to add citation information once we have metadata which would make #52 much easier to solve.

## Downsides

- Someone would have to go through the repo and create the initial listings. (I'd be willing to do this, but it would take some to verify the listings)
- This would also add some friction to how people add papers to the repo, as they would commit to the listing and then compiling those changes down to the readme. Not to mention it would be a departure from how things are done currently.

I'd be great to hear everyones thoughts on this before I proceed.

**Comment by DarrenN** [comment]
@devinmcgloin thanks for putting this together

> It seems like the best way to go about this is to standardize the format in which people add papers to the repo in the first place.

Please take a stab at coming up with a common data format. Might I suggest leveraging fields similar to [Bibtex](http://www.bibtex.org/)? YAML or JSON is fine. 

> Someone would have to go through the repo and create the initial listings. (I'd be willing to do this, but it would take some to verify the listings)

I had pursued automating this a while back. My initial thought was to write some code that traversed the repo locally, inspecting the PDFs and gathering metadata on them from search services. Using `pdf2xml` I was able to convert PDFs to XML so I could:

- Use x-path to extract the title of the paper (with some dodgy heuristics)
- Search [DBLP](http://dblp.uni-trier.de/) with the title and pick the best guess from the results by calculating the levenshtein distance of the titles. DBLP provides [Bibtex](http://www.bibtex.org/) information on the paper, which could be quickly translated into a JSON or YAML format.

That wouldn't do much for papers that are scans without text information, and sometimes DBLP doesn't have an entry for a paper. So we would need to manually deal with those cases. Side note: I found the Microsoft Academic API to be really, really bad, but maybe that has changed since I last looked at it.

Happy to share those scripts, they're in Racket but you could easily port them to another language.

> This would also add some friction to how people add papers to the repo,

Yes it would but I don't think it would be unreasonable. In regards to compilation: we could kick that off with a webhook call or a cron job on the same server that compiles and builds paperswelove.org

**Comment by mrallen1** [comment]
I wonder if it would be easiest to take the paper title and its primary author(s) and just use an academic search engine like [Microsoft's](https://academic.microsoft.com) or [Google's](https://scholar.google.com) to collect the metadata/BibTex you're looking for.

Here's _Time, Clocks and the Ordering of Events in a Distributed System_ data from [Microsoft](https://academic.microsoft.com/#/detail/1973501242) and [Google](https://scholar.google.com/scholar?hl=en&q=Time+Clocks+and+The+ordering+of+events&btnG=&as_sdt=1%2C44&as_sdtp=)

I also vaguely remember that Microsoft made it's corpus of research paper data available as a download but I can't locate it right now. Maybe that could be your index.

**Comment by devinmcgloin** [comment]
Great, thanks for the response. 

Looks like working with google should be easy due to [scholar.py](https://github.com/ckreibich/scholar.py)

The listings should probably be in yaml if the user is going to edit them directly. I'll write a script that normalizes the `.yml` listings in one pass and generates the appropriate bibtex citations and readme files that we can run with the cron job. Generating the initial listings is more of a one off task, but I can include the script for that as well if you think it'd be useful. 

I'm thinking the `yaml` would look something like this if its agreeable: 

```yml 
- title: Time, clocks, and the ordering of events in a distributed system
  authors: ["Leslie Lamport"]
  year: 1978
  abstract: The concept of one event happening before another in a distributed system is examined...
  local: False
  desc: Lamport shows that it is possible to achieve a partial ordering ... 
```

I'll also chat with some of the folks over at the Courant Library, they might have some recommendations for other data sources we can look into.

**Comment by NewAlexandria** [comment]
👍 
This is a nice approach.  Not too much to ask maintainers to format the JSON file, if a contributor doesn't complete the PR.

**Comment by hakutsuru** [comment]
Great to see progress on this.

I am a little bit confused about the format though.

Would the yaml data be in a large index? Would there an index for every directory?

Would these be sidecar-style metadata files, like those for photographs? (Which would be like "paper-title.pdf" and "paper-title.yml", and if so, how would linked publications be handled.)

This is brought to mind by experiences with asset management, because what I am not seeing in the publication schema is the pdf location, or uri reference.

Aside from tooling to surface newly added publications, I suspect we would want a way to check the publication metadata against the repo (files and readme's), and the other way around -- to see if there are any discrepancies in either direction.

Hopefully this makes sense. The publication data is great, yet if there is no reference to where in the repo an item would be found, there is no way to audit an entry other than full-text searching of the repo.

(And I may be completely wrong about how useful that would be...)

**Comment by devinmcgloin** [comment]
@hakutsuru those are all good points. Hopefully this clarifies my approach. 

>Would the yaml data be in a large index? Would there an index for every directory?

I was planning on doing this on a per directory basis, there would be one yaml listing per directory from which we could very easily create a larger index for searching on the pwl site or elsewhere. 

> I am not seeing in the publication schema is the pdf location, or uri reference.

Apologies on that front, you're absolutely right. It should have a URI attached to each listing. For external listings we would have to provide a external URI. For papers in the repo it would be best to have a URI as well, however it seems as though github has removed the ability to view pdfs in the browser and replaced it with an link that auto downloads the pdf. This probably isn't the behavior we would want. For very little cost we could probably put them at papers.paperswelove.org, but I'll defer to @DarrenN on this. 

> I suspect we would want a way to check the publication metadata against the repo (files and readme's), and the other way around -- to see if there are any discrepancies in either direction.

The way I was approaching it was focused on having papers added to the yaml listings only, from which we can generate readme and bibtex files. In order to add a new paper we would just add the listing and on a daily basis we would generate the other files. This also means a common format for the readme, which we would need to agree upon.

**Comment by DarrenN** [comment]
> For very little cost we could probably put them at papers.paperswelove.org

Are you thinking of mirroring the PDFs on S3?

**Comment by devinmcgloin** [comment]
I think that would be a good solution to github automatically downloading them. Shouldn't be that expensive but you know the traffic levels much better than I do.

**Comment by DarrenN** [comment]
@devinmcgloin I'm fine with mirroring on S3.

**Comment by DarrenN** [comment]
@zeeshanlakhani once we get closer on this, let's setup a bucket and CNAME for `paperswelove.org` similar to what we did for `pwlconf.org` to serve the PDFs off S3.

**Comment by jeremyheiler** [comment]
@DarrenN, I can setup the CNAME.

However, I wondering if we should bother keeping this repo as the UX for PWL papers. Rather, we store the papers and their metadata in this repo, and generate an HTML site, with a page per paper, links to mirrored papers on S3 (or from GitHub). This could open up some interesting features down the road, like a proper search, and perhaps tags rather than categories.

**Comment by DarrenN** [comment]
@jeremyheiler I like that idea, lemme think on it some more. I've been working up some code to partially automate some of this.

**Comment by DarrenN** [comment]
Also might be a good time to talk to Chas about using his PDF ripping service to see what we can extract from the papers themselves.

**Comment by baerbock** [comment]
@DarrenN Any progress on metadata?

**Comment by DarrenN** [comment]
@baerbock kinda sorta -> https://github.com/papers-we-love/papers-we-love/blob/master/nautilus.db and https://darrenn.github.io/nautilus/index.html

**Comment by maximveksler** [comment]
Another option would be to use json-ld to express semantic structure. https://en.wikipedia.org/wiki/Bibliographic_Ontology
