### ISSUE TITLE
Merge categories: GC and memory mgt

### ISSUE THREAD

**Issue by NewAlexandria** [papers-we-love/papers-we-love#560]
When talkign about #559 I realized that there were other folders that have maybe gotten _wooly_.

Particularly, these concepts are similar enough, and contain overlapping papers:

* https://github.com/papers-we-love/papers-we-love/tree/master/garbage_collection
* https://github.com/papers-we-love/papers-we-love/tree/master/memory_management

I wanted to solicit thoughts before I PR'd it.	 

Perhaps `memory_management` can hold a `GC` group of papers?

**Comment by hakutsuru** [comment]
Commenting here, since this is the earliest entry prompted by the discussion in Issue #559.

Unfortunately, many of us are busy with preparation for PWLConf (https://pwlconf.org). So the core team may be distracted until after the conference.

Efforts to improve discoverability are great, but naming is often subjective. For instance, I am not certain the changes in `group pattern-* related papers` (#564) are helpful, whereas `Rename "paradigm" and "plt" folders for findability` (#561) seems a more obvious win -- but then I wonder if omitting _programming_ from these categories is helpful.

I would propose we add brief context statement to topic readmes (where helpful), with perhaps a wikipedia link, links to related topics in the papers-we-love repo, and related terms. If the goal is discoverability, we should work to improve this, since an ideal organization of materials will be impossible to achieve.

**Comment by NewAlexandria** [comment]
I updated the [`pattern-` related PR](https://github.com/papers-we-love/papers-we-love/pull/564) per your suggestion.  

I agree that the programming language group needs more cleanup.  Actually, `PLT` exists in two files, and some other consolidation to propose

**Comment by niudage** [comment]
thankyou goodproject
